name: CI with Doppler & New Relic
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Install Doppler CLI
        run: curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh

      - name: Test app with Doppler (New Relic enabled)
        run: |
          # Roda a app em background com secrets do Doppler
          doppler run --command="python app/app.py" &
          sleep 3

          # Verifica se a app responde
          curl -f http://localhost:5000/health

          # Verifica se o New Relic foi ativado (opcional, mas elegante)
          curl -s http://localhost:5000 | grep -q '"newrelic_enabled": true' && echo "✅ New Relic enabled" || echo "⚠️ New Relic not active (check Doppler config)"
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}