name: CI with Doppler & New Relic
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Install Doppler CLI (binary)
        run: curl -Ls --tlsv1.2 --proto "=https" https://cli.doppler.com/install.sh | sh -s -- --no-package-manager

      - name: Test app with Doppler
        run: |
          doppler run --project infra-pipeline-poa --config dev --command="python app/app.py" &
          sleep 3
          curl -f http://localhost:5000/health
          response=$(curl -s http://localhost:5000)
          if echo "$response" | grep -q '"newrelic_enabled": true'; then
            echo "✅ New Relic enabled via Doppler"
          else
            echo "❌ New Relic not active — check Doppler project/config"
            exit 1
          fi
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}