name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run health check
        run: |
          python app/app.py &
          sleep 2
          curl -f http://localhost:5000/health